version: '3.3'

services:
   webserver:
     image: nginx:1.15.12-alpine
     container_name: webserver
     restart: always
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./nginx-conf:/etc/nginx/conf.d
       - certbot-etc:/etc/letsencrypt
     networks:
       - app-network     
   certbot:
     depends_on:
      - webserver
     image: certbot/certbot
     container_name: certbot
     volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
     command: certonly --webroot --webroot-path=/var/www/html --email <email> --agree-tos --no-eff-email --staging -d <host_name> 
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     networks:
       - app-network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: <PASSWORD> 
       MYSQL_DATABASE: <DB_NAME>
       MYSQL_USER: <DB_USER>
       MYSQL_PASSWORD: <DB_PASSWORD>
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports: 
       - "8080:80"
     networks:
       - app-network
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: <PASSWORD> 
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     volumes: ["./:/var/www/html"]
     networks:
       - app-network
     environment:
       WORDPRESS_DB_HOST: <DB:PORT> 
       WORDPRESS_DB_USER: <USER>
       WORDPRESS_DB_PASSWORD: <PASSWORD> 
       WORDPRESS_DB_NAME: <DB_NAME>
volumes:
   certbot-etc:
   wordpress:
   db_data:

networks:
  app-network:
    driver: bridge


